export const copy = {
  en: {
    appName: "SHUNO",
    appSubtitle: "Voice-Enabled Clinical Assessment",
    appTagline: "Streamline patient consultations with AI-assisted voice history taking",
    appDescription: "Fast, accurate, and accessible medical history documentation for rural health centers",
    uhc: "Union Health Complex",
    forStaffOnly: "For use by UHC staff only",
    lang: "Language",
    english: "English",
    bangla: "বাংলা",

    nav: {
      dashboard: "Dashboard",
      newIntake: "New Intake",
      patients: "Patients",
      history: "History",
    },

    dashboard: {
      welcome: "Welcome",
      todayIntakes: "Intakes today",
      startNew: "Start new intake",
      startNewSub: "Record patient history by voice",
      registerPatient: "Register patient",
      registerPatientSub: "Add new patient to the system",
      recentIntakes: "Recent intakes",
      noRecent: "No intakes yet. Start one above.",
      viewAll: "View all",
    },

    voice: {
      title: "Voice intake",
      subtitle: "Record patient history in Bangla or English",
      instructionTitle: "Instructions for the patient",
      instruction1: "Press the microphone button below and describe your symptoms or health problem in your own words (Bangla or English).",
      instruction2: "Press the button again when you have finished speaking.",
      instruction3: "Speak clearly and at a normal pace. You can take your time.",
      waveformLabel: "Sound level",
      recordStart: "Press to start recording",
      recordStop: "Press to stop recording",
      recording: "Recording…",
      sending: "Sending for transcription…",
      transcribing: "Transcribing… Please wait.",
      done: "Done.",
      noAudio: "No audio was recorded. Please try again.",
      transcript: "Transcript",
      transcriptPlaceholder: "Transcript will appear here after recording.",
      errorMic: "Please allow microphone access in your browser settings.",
      errorNetwork: "Connection problem. Check your internet and try again.",
      errorTranscription: "Transcription failed. Please try again.",
      retry: "Try again",
      newIntake: "Start another intake",
      backToDashboard: "Back to dashboard",
      demoNotice: "Transcription service was unavailable. Your recording was saved. Check internet and OPENAI_API_KEY in .env, then retry for real transcription.",
      debugLink: "Open /api/transcribe in a new tab to see why (connectivity check).",
      browserOnly: "Free · No limit · Uses your browser only",
      improveWithCloud: "Improve with cloud (OpenAI)",
      noSpeechDetected: "No speech detected. Try speaking again or use cloud transcription below.",
      speechUnavailable: "Browser speech not available. Use cloud transcription below.",
      translationLabel: "English",
      translationLoading: "Translating…",
      reviewTitle: "Review & Approve",
      reviewSubtitle: "Review the following information before saving",
      approveAndSave: "Approve & Save",
      discard: "Discard",
      clinicalSummaryLabel: "Clinical Summary",
      transcriptLabel: "Original Transcript",
      quickRegisterError:
        "Could not register patient. Check your connection. On Netlify: set DATABASE_URL (e.g. Neon) or UHC_DEMO_MODE=true.",
    },

    patients: {
      title: "Patients",
      subtitle: "Register and manage patients",
      registerNew: "Register new patient",
      noPatients: "No patients registered yet.",
      noPatientsSub: "Register a patient to link them to voice intakes.",
      name: "Full name",
      namePlaceholder: "Patient full name",
      age: "Age",
      agePlaceholder: "Years",
      gender: "Gender",
      genderOption: "Select",
      male: "Male",
      female: "Female",
      other: "Other",
      village: "Village / area",
      villagePlaceholder: "Village or area name",
      phone: "Phone number",
      phonePlaceholder: "01XXXXXXXXX",
      nationalId: "National ID",
      nationalIdPlaceholder: "Enter National ID number",
      submit: "Register patient",
      back: "Back",
      registered: "Patient registered successfully.",
      searchPlaceholder: "Search by name, village, phone, or ID...",
      noResults: "No patients found",
      showingResults: "Showing {count} of {total} patients",
      expand: "View details",
      collapse: "Collapse",
      edit: "Edit",
      save: "Save",
      delete: "Delete",
      cancel: "Cancel",
      confirmDelete: "Are you sure you want to delete this patient? All related intakes will be unlinked.",
      apiError: "Request failed. Check your connection or Netlify DATABASE_URL / demo mode.",
      intakesForPatient: "Intakes for this patient",
      noIntakesForPatient: "No intakes recorded yet for this patient",
      patientInfo: "Patient Information",
      updated: "Patient updated successfully",
      totalPatients: "Total Patients",
      clickToExpand: "Click to expand and view details",
      editingMode: "Editing mode",
      requiredField: "Required field",
    },

    history: {
      title: "Intake history",
      subtitle: "Past voice intakes and transcripts",
      noHistory: "No intake history yet.",
      noHistorySub: "Voice intakes will appear here.",
      date: "Date",
      patient: "Patient",
      transcript: "Transcript",
      clinicalSummary: "Clinical Summary",
      viewTranscript: "View transcript",
      viewDetails: "View details",
      copy: "Copy",
      copied: "Copied to clipboard",
    },

    common: {
      back: "Back",
      loading: "Loading…",
      save: "Save",
      cancel: "Cancel",
    },

    login: {
      title: "Medical History Intake",
      subtitle: "Sign in to access the voice intake system",
      email: "Email",
      emailPlaceholder: "doctor@shuno.online",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Sign in",
      signingIn: "Signing in…",
      error: "Invalid email or password.",
      signOut: "Sign out",
      secureNote: "Secure login. Your data is encrypted and protected.",
      forgotPassword: "Forgot password?",
      forgotEmail: "Forgot email?",
    },
  },
  bn: {
    appName: "শুনো",
    appSubtitle: "কণ্ঠ-সক্ষম ক্লিনিকাল মূল্যায়ন",
    appTagline: "এআই-সহায়তা কণ্ঠে ইতিহাস নেওয়ার মাধ্যমে রোগীর পরামর্শ সহজ করুন",
    appDescription: "গ্রামীণ স্বাস্থ্য কেন্দ্রের জন্য দ্রুত, নির্ভুল এবং সহজলভ্য চিকিৎসা ইতিহাস নথি",
    uhc: "ইউনিয়ন স্বাস্থ্য কমপ্লেক্স",
    forStaffOnly: "শুধুমাত্র ইউএইচসি স্টাফের ব্যবহারের জন্য",
    lang: "ভাষা",
    english: "English",
    bangla: "বাংলা",

    nav: {
      dashboard: "ড্যাশবোর্ড",
      newIntake: "নতুন সাক্ষাত্কার",
      patients: "রোগী",
      history: "ইতিহাস",
    },

    dashboard: {
      welcome: "স্বাগতম",
      todayIntakes: "আজকের সাক্ষাত্কার",
      startNew: "নতুন সাক্ষাত্কার শুরু করুন",
      startNewSub: "কণ্ঠে রোগীর ইতিহাস রেকর্ড করুন",
      registerPatient: "রোগী নিবন্ধন করুন",
      registerPatientSub: "নতুন রোগী যুক্ত করুন",
      recentIntakes: "সাম্প্রতিক সাক্ষাত্কার",
      noRecent: "এখনও সাক্ষাত্কার নেই। উপরে থেকে শুরু করুন।",
      viewAll: "সব দেখুন",
    },

    voice: {
      title: "কণ্ঠে বলুন",
      subtitle: "বাংলা বা ইংরেজিতে রোগীর ইতিহাস রেকর্ড করুন",
      instructionTitle: "রোগীকে বলুন",
      instruction1: "নিচের মাইক্রোফোন বাটনে চাপুন এবং আপনার লক্ষণ বা স্বাস্থ্য সমস্যা নিজের ভাষায় (বাংলা বা ইংরেজি) বলুন।",
      instruction2: "বলতে শেষ হলে আবার বাটনে চাপুন।",
      instruction3: "স্পষ্ট এবং স্বাভাবিক গতিতে বলুন। সময় নিতে পারেন।",
      waveformLabel: "শব্দের মাত্রা",
      recordStart: "রেকর্ড শুরু করতে চাপুন",
      recordStop: "বন্ধ করতে চাপুন",
      recording: "রেকর্ডিং…",
      sending: "ট্রান্সক্রিপশনের জন্য পাঠানো হচ্ছে…",
      transcribing: "টাইপ করা হচ্ছে… অপেক্ষা করুন।",
      done: "সম্পন্ন।",
      noAudio: "কোন অডিও রেকর্ড হয়নি। আবার চেষ্টা করুন।",
      transcript: "ট্রান্সক্রিপ্ট",
      transcriptPlaceholder: "রেকর্ডের পর এখানে ট্রান্সক্রিপ্ট দেখা যাবে।",
      errorMic: "ব্রাউজার সেটিংসে মাইক্রোফোন অনুমতি দিন।",
      errorNetwork: "ইন্টারনেট সংযোগ পরীক্ষা করুন এবং আবার চেষ্টা করুন।",
      errorTranscription: "ট্রান্সক্রিপশন হয়নি। আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      newIntake: "আরেকটি সাক্ষাত্কার শুরু করুন",
      backToDashboard: "ড্যাশবোর্ডে ফিরে যান",
      demoNotice: "ট্রান্সক্রিপশন সার্ভিস পৌঁছানো যায়নি। রেকর্ড সংরক্ষিত। ইন্টারনেট ও .env এ OPENAI_API_KEY চেক করুন, তারপর আবার চেষ্টা করুন।",
      debugLink: "কেন হয়েছে দেখতে নতুন ট্যাবে /api/transcribe খুলুন।",
      browserOnly: "বিনামূল্যে · সীমা নেই · শুধু ব্রাউজার",
      improveWithCloud: "ক্লাউড দিয়ে উন্নত করুন (OpenAI)",
      noSpeechDetected: "কোনো কথা শোনা যায়নি। আবার বলুন বা নিচে ক্লাউড ট্রান্সক্রিপশন ব্যবহার করুন।",
      speechUnavailable: "ব্রাউজার স্পিচ চালু নেই। নিচে ক্লাউড ট্রান্সক্রিপশন ব্যবহার করুন।",
      translationLabel: "ইংরেজি",
      translationLoading: "অনুবাদ করা হচ্ছে…",
      reviewTitle: "পর্যালোচনা এবং অনুমোদন",
      reviewSubtitle: "সংরক্ষণ করার আগে নিম্নলিখিত তথ্য পর্যালোচনা করুন",
      approveAndSave: "অনুমোদন ও সংরক্ষণ",
      discard: "বাতিল করুন",
      clinicalSummaryLabel: "ক্লিনিকাল সংক্ষিপ্তসার",
      transcriptLabel: "মূল ট্রান্সক্রিপ্ট",
      quickRegisterError:
        "রোগী নিবন্ধন হয়নি। নেটওয়ার্ক চেক করুন। Netlify-তে DATABASE_URL (যেমন Neon) বা UHC_DEMO_MODE=true সেট করুন।",
    },

    patients: {
      title: "রোগী",
      subtitle: "রোগী নিবন্ধন ও পরিচালনা",
      registerNew: "নতুন রোগী নিবন্ধন",
      noPatients: "এখনও কোনো রোগী নিবন্ধন হয়নি।",
      noPatientsSub: "কণ্ঠে সাক্ষাত্কারের সাথে যুক্ত করতে রোগী নিবন্ধন করুন।",
      name: "পূর্ণ নাম",
      namePlaceholder: "রোগীর পূর্ণ নাম",
      age: "বয়স",
      agePlaceholder: "বছর",
      gender: "লিঙ্গ",
      genderOption: "নির্বাচন করুন",
      male: "পুরুষ",
      female: "মহিলা",
      other: "অন্যান্য",
      village: "গ্রাম / এলাকা",
      villagePlaceholder: "গ্রাম বা এলাকার নাম",
      phone: "মোবাইল নম্বর",
      phonePlaceholder: "০১XXXXXXXXX",
      nationalId: "জাতীয় পরিচয়পত্র নম্বর",
      nationalIdPlaceholder: "জাতীয় পরিচয়পত্র নম্বর লিখুন",
      submit: "রোগী নিবন্ধন করুন",
      back: "পিছনে",
      registered: "রোগী সফলভাবে নিবন্ধন হয়েছে।",
      searchPlaceholder: "নাম, গ্রাম, ফোন বা আইডি দিয়ে খুঁজুন...",
      noResults: "কোনো রোগী পাওয়া যায়নি",
      showingResults: "{total} এর মধ্যে {count} জন রোগী দেখানো হচ্ছে",
      expand: "বিস্তারিত দেখুন",
      collapse: "সংকুচিত করুন",
      edit: "সম্পাদনা",
      save: "সংরক্ষণ",
      delete: "মুছুন",
      cancel: "বাতিল",
      confirmDelete: "আপনি কি নিশ্চিত যে আপনি এই রোগীকে মুছতে চান? সমস্ত সংশ্লিষ্ট ইনটেক আনলিঙ্ক করা হবে।",
      apiError: "অনুরোধ ব্যর্থ। সংযোগ বা Netlify DATABASE_URL / ডেমো মোড চেক করুন।",
      intakesForPatient: "এই রোগীর ইনটেক",
      noIntakesForPatient: "এই রোগীর জন্য এখনও কোনো ইনটেক রেকর্ড করা হয়নি",
      patientInfo: "রোগীর তথ্য",
      updated: "রোগী সফলভাবে আপডেট হয়েছে",
      totalPatients: "মোট রোগী",
      clickToExpand: "বিস্তারিত দেখতে ক্লিক করুন",
      editingMode: "সম্পাদনা মোড",
      requiredField: "প্রয়োজনীয়",
    },

    history: {
      title: "সাক্ষাত্কারের ইতিহাস",
      subtitle: "পূর্বের কণ্ঠে সাক্ষাত্কার ও ট্রান্সক্রিপ্ট",
      noHistory: "এখনও সাক্ষাত্কারের ইতিহাস নেই।",
      noHistorySub: "কণ্ঠে সাক্ষাত্কার এখানে দেখা যাবে।",
      date: "তারিখ",
      patient: "রোগী",
      transcript: "ট্রান্সক্রিপ্ট",
      clinicalSummary: "ক্লিনিকাল সংক্ষিপ্তসার",
      viewTranscript: "ট্রান্সক্রিপ্ট দেখুন",
      viewDetails: "বিস্তারিত দেখুন",
      copy: "কপি করুন",
      copied: "ক্লিপবোর্ডে কপি হয়েছে",
    },

    common: {
      back: "পিছনে",
      loading: "লোড হচ্ছে…",
      save: "সংরক্ষণ",
      cancel: "বাতিল",
    },

    login: {
      title: "মেডিকেল হিস্টরি ইনটেক",
      subtitle: "কণ্ঠে সাক্ষাত্কার সিস্টেমে প্রবেশ করতে সাইন ইন করুন",
      email: "ইমেইল",
      emailPlaceholder: "doctor@shuno.online",
      password: "পাসওয়ার্ড",
      passwordPlaceholder: "আপনার পাসওয়ার্ড লিখুন",
      submit: "সাইন ইন",
      signingIn: "সাইন ইন হচ্ছে…",
      error: "ইমেইল বা পাসওয়ার্ড ভুল।",
      signOut: "সাইন আউট",
      secureNote: "নিরাপদ লগইন। আপনার তথ্য এনক্রিপ্টেড এবং সুরক্ষিত।",
      forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
      forgotEmail: "ইমেইল ভুলে গেছেন?",
    },
  },
};

export const defaultLang = "bn";
